enum NAPOJE {
	NAPOJE_ZERO = "NAPOJE ZERO",
	NAPOJE = "NAPOJE",
	NAPOJE_GAZOWANE = "NAPOJE GAZOWANE",
	NAPOJE_NIEGAZOWANE = "NAPOJE NIEGAZOWANE",
}
enum ALKOHOL {
	PIWO = "PIWO",
	WÓDKA = "WÓDKA",
	WINA = "WINA",
	WHISKY = "WHISKY",
	RUM = "RUM",
	LIKIER = "LIKIER",
	GIN = "GIN",
}
enum WIĘCEJ {
	ONE = "ONE",
	TWO = "TWO",
	THREE = "THREE",
	FOUR = "FOUR",
	FIVE = "FIVE",
}

export { NAPOJE, ALKOHOL, WIĘCEJ };
